spring:
  data:
    mongodb:
      uuid-representation: standard
      # uri: mongodb+srv://grupo2:w8IIEs2mmNhTwdIN@jupm2digital.uikcavy.mongodb.net/
      # uri: mongodb://admin_challenge:BYBcMJEEWw5egRUo@localhost:27017/Skins
      uri: mongodb://admin_user:BYBcMJEEWw5egRUo@localhost:27017/test
      database: Barrio

