spring:
  application:
    name: jump2digital
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    enabled: true
  data:
    mongodb:
      uri: mongodb://admin_challenge:BYBcMJEEWw5egRUo@localhost:27017/challenges
      uuid-representation: standard

server:
  port: 8762

custom:
  jsonFile:
    filePath: "C:/Users/pedro/Documents/PROGRAMACION/PROYECTOS/jump2digital/src/main/resources/skins.json"
